export const mockGearItems = [
  {
    id: "1",
    name: "Backpack",
    brand: "Osprey",
    weight: 1500,
    weightUnit: "g",
    category: "Backpacks",
    price: 250,
    currency: "USD",
  },
  {
    id: "2",
    name: "Tent",
    brand: "Big Agnes",
    weight: 2000,
    weightUnit: "g",
    category: "Shelter",
    price: 400,
    currency: "USD",
  },
  {
    id: "3",
    name: "Sleeping Bag",
    brand: "Therm-a-Rest",
    weight: 1000,
    weightUnit: "g",
    category: "Sleep System",
    price: 300,
    currency: "USD",
  },
]
